### ISSUE TITLE
GitHub WikiHouse: Add some owners?

### ISSUE THREAD

**Issue by theo-armour** [micrypt/micrypt.github.com#1]
Hi @micrypt 

Please accept my apologies for contacting you in this manner, but I could find no other easy manner.

I see you are one of the owners of http://github.com/wikihouse.

Would it be possible for you to add some new owners to the organization?

It would be great if you could add Alastair Parvin - but I cannot seem to find a GitHub user name for Alastair. ;-(

Also can you add @alexykot and myself @theo-armour?

You can see demos that I would like to add add here:

[Display WikiHouse Studio2](http://theo-armour.github.io/theo-armour.testing/display-wikihouse-studio2/latest/index.html)
- takes too long to load but working on improving this...

[Display WikiHouse StepUp1](http://theo-armour.github.io/theo-armour.testing/display-wikihouse-stepup1/latest/index.html)

[Display WikiHouse Mallet1](http://theo-armour.github.io/theo-armour.testing/display-wikihouse-mallet1/latest/index.html) 

Theo

**Comment by micrypt** [comment]
@theo-armour What’s your email address? @tav will be in touch.

**Comment by theo-armour** [comment]
Hi Seyi

Thanks for the speedy reply.

My email is [redacted].

I look forward to hearing from @tav

Theo

**Comment by micrypt** [comment]
@theo-armour You’re welcome. Passed on the message, and redacted your email address. Closing this issue.
